#მომხმარებელს შემოვატანინე 4 სხავდასხვა რიცხვი და ამ ოთხივე რიცხვზე მოვახდინე არითმეტიკური ოპერაციები. +,-,*,//
user_age=input('enter your age')
user_height=input('enter your height')
user_moms_age=input('enter your moms age')
user_moms_height=input('enter your moms height')

print(user_age +2)
print(user_age-2)
print(user_age/2)
print(user_age//2)
print(user_age*2)
print(user_height+2)
print(user_height-2)
print(user_height/2)
print(user_height//2)
print(user_height*2)
print(user_moms_age+2)
print(user_moms_age-2)
print(user_moms_age/2)
print(user_moms_age//2)
print(user_moms_age*2)
print(user_moms_height+2)
print(user_moms_height-2)
print(user_moms_height*2)
print(user_moms_height/2)
print(user_moms_height//2)