number=int(input('enter your number 1 to 101: '))
my_number=1

while my_number!=number:
     my_number=2
while my_number!=number:
     my_number=3
while my_number!=number:
    my_number=4
while my_number!=number:
     my_number=5
while my_number!=number:
     my_number=6
while my_number!=number:
     my_number=7
while my_number!=number:
     my_number=8
while my_number!=number:
     my_number=9
while my_number!=number:
     my_number=10
while my_number!=number:
     my_number=11
while my_number!=number:
     my_number=12
while my_number!=number:
     my_number=13
while my_number!=number:
     my_number=14
while my_number!=number:
     my_number=15
while my_number!=number:
     my_number=16
while my_number!=number:
     my_number=17
while my_number!=number:
     my_number=18
while my_number!=number:
     my_number=19
while my_number!=number:
     my_number=20
while my_number!=number:
     my_number=21
while my_number!=number:
     my_number=22
while my_number!=number:
     my_number=23
while my_number!=number:
     my_number=24
while my_number!=number:
     my_number=25
while my_number!=number:
     my_number=26
while my_number!=number:
     my_number=27
while my_number!=number:
     my_number=28
while my_number!=number:
     my_number=29
while my_number!=number:
     my_number=30
while my_number!=number:
     my_number=31
while my_number!=number:
     my_number=32
while my_number!=number:
     my_number=33
while my_number!=number:
     my_number=34
while my_number!=number:
     my_number=35
while my_number!=number:
     my_number=36
while my_number!=number:
     my_number=37
while my_number!=number:
     my_number=38
while my_number!=number:
     my_number=39
while my_number!=number:
     my_number=40
while my_number!=number:
     my_number=41
while my_number!=number:
     my_number=42
while my_number!=number:
     my_number=43
while my_number!=number:
     my_number=44
while my_number!=number:
     my_number=45
while my_number!=number:
     my_number=46
while my_number!=number:
     my_number=47
while my_number!=number:
     my_number=48
while my_number!=number:
     my_number=49
while my_number!=number:
     my_number=50
while my_number!=number:
     my_number=51
while my_number!=number:
     my_number=52
while my_number!=number:
     my_number=53
while my_number!=number:
     my_number=54
while my_number!=number:
     my_number=55
while my_number!=number:
     my_number=56
while my_number!=number:
     my_number=57
while my_number!=number:
     my_number=58
while my_number!=number:
     my_number=59
while my_number!=number:
     my_number=60
while my_number!=number:
     my_number=61
while my_number!=number:
     my_number=62
while my_number!=number:
     my_number=63
while my_number!=number:
     my_number=64
while my_number!=number:
     my_number=65
while my_number!=number:
     my_number=66
while my_number!=number:
     my_number=67
while my_number!=number:
     my_number=68
while my_number!=number:
     my_number=69
while my_number!=number:
     my_number=70
while my_number!=number:
     my_number=71
while my_number!=number:
     my_number=72
while my_number!=number:
     my_number=73
while my_number!=number:
     my_number=74
while my_number!=number:
     my_number=75
while my_number!=number:
     my_number=76
while my_number!=number:
     my_number=77
while my_number!=number:
     my_number=78
while my_number!=number:
     my_number=79
while my_number!=number:
     my_number=80
while my_number!=number:
     my_number=81
while my_number!=number:
     my_number=82
while my_number!=number:
     my_number=83
while my_number!=number:
     my_number=84
while my_number!=number:
     my_number=85
while my_number!=number:
     my_number=86
while my_number!=number:
     my_number=87
while my_number!=number:
     my_number=88
while my_number!=number:
     my_number=89
while my_number!=number:
     my_number=90
while my_number!=number:
     my_number=91
while my_number!=number:
     my_number=92
while my_number!=number:
     my_number=93
while my_number!=number:
     my_number=94
while my_number!=number:
     my_number=95
while my_number!=number:
     my_number=96
while my_number!=number:
     my_number=97
while my_number!=number:
     my_number=98
while my_number!=number:
     my_number=99
while my_number!=number:
     my_number=100

    
else:
     print('i guest it correctly! ')

 